version: "3.8"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5127:5127"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Server=db;Database=videoGames;User=sa;Password=P@ssw0rd;TrustServerCertificate=True;
        restart: always
        depends_on:
            - db

    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P@ssw0rd
        ports:
            - "1433:1433"
        restart: always
