services:
  webapi:
    build:
      context: ./VideoGames
      dockerfile: Dockerfile
    image: video-games-server:v4
    container_name: webapi
    ports:
      - "5127:5127"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=videoGames;User=sa;Password=password;TrustServerCertificate=True;
    networks:
      - my_network
    # restart: always
    # depends_on:
    #   - db

networks:
  my_network:
    driver: bridge

# Commented out database service
# db:
#   image: mcr.microsoft.com/mssql/server:2022-latest
#   environment:
#     - ACCEPT_EULA=Y
#     - SA_PASSWORD=password
#   ports:
#     - "1433:1433"
#   restart: always